### ISSUE TITLE
Pine64 won't start, even after editing uEnv

### ISSUE THREAD

**Issue by Nittola** [ayufan-pine64/android-6.0#3]
When I try to turn on my Pine64, the red led turn on for some seconds and then turn off. I posted the problem in the forum, I tried all the solutions but still it doesn't work. Here's a screenshot

![ss 2016-12-17 at 10 45 05](https://cloud.githubusercontent.com/assets/24627626/21289951/899aa8d6-c4aa-11e6-9567-85e63335bf33.png)

Could someone tell me how to fix the problem or attach their uEnv? I need 1080p60 and no limit of download on ethernet.

Here's my [uEnv.txt](https://github.com/ayufan-pine64/android-6.0/files/659105/uEnv.txt)

**Comment by mfjnext** [comment]
There should be no space before :
cma=384m
disp_mode=1080p60
eth0_speed=auto
hdmi_cec=2
