### ISSUE TITLE
Ethernet settings window is not available in latest release

### ISSUE THREAD

**Issue by slapin** [ayufan-pine64/android-6.0#4]
I have basic pine64 board without wifi/bluetooth module.
I downloaded latest release image. The Settings/Networking/more doesn't contain ethernet option.
The device reports is is offline. Stock 5.1 image works fine on this board. Any ideas?

Correction: Ethernet works if set to fixed 100 via uEnv.txt. All other gigabit devices work fine on this switch,
so it looks like hardware or driver problem. But ethernet settings window is still not available.

**Comment by slapin** [comment]
Well, correction - ethernet works if I set fixed speed to 100, which means it is probably hardware
or drivers issue. But settings window for ethernet is still not available. Also, if I select
Data usage/ETHERNET settings application crash. I don't see a way to have adb access on this board to
provide better report :(

**Comment by apspurgeon** [comment]
I have same issue, it works but I don't have an ethernet option in settings.  Importantly, Netflix reports it doesn't see the network and won't run  (all other apps work/use network ok)

**Comment by ayufan** [comment]
Ethernet settings will not be available in my builds.
