### ISSUE TITLE
lunch failed help

### ISSUE THREAD

**Issue by hzlijianjun** [ayufan-pine64/android-6.0#8]
After I choose one luch menu item, the process incurr error as following image.
![lunch-error](https://cloud.githubusercontent.com/assets/1620094/23981967/4fca0710-0a45-11e7-818e-8d2bb19a825e.jpg)

Best regard
Jungle

**Comment by deskwizard** [comment]
- Redacted

**Comment by ayufan** [comment]
Please, update sources.
